In [ ]:
import zipfile
with zipfile.ZipFile("../data/raw/orders_product_prior.parquet.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

In [ ]:
import pandas as pd
SQL_URL = "https:/raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/"
TO_SAVE_URL = 'C:/Users/Dell/ACA/sql-analytics-portfolio/Data/Old_schemas/'
l = ['customers', 'employees','orders','products', 'sales']

for i in l:
    print(100*'-')
    print(f"trying to download {i}.csv")
    df = pd.read_csv(SQL_URL+i+'.csv')
    print(f"{i}.csv is downloaded")
    print(f"the shape of {i}.csv : {df.shape}")
    print(f"trying to save  {i}.csv")
    df.to_csv(TO_SAVE_URL+i+'.csv',index=False)
    print(f"{i}.csv is successfully saved")

----------------------------------------------------------------------------------------------------
trying to download customers.csv
customers.csv is downloaded
the shape of customers.csv : (2000, 5)
trying to save  customers.csv
customers.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download employees.csv
employees.csv is downloaded
the shape of employees.csv : (100, 5)
trying to save  employees.csv
employees.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download orders.csv
orders.csv is downloaded
the shape of orders.csv : (200, 5)
trying to save  orders.csv
orders.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download products.csv
products.csv is downloaded
the shape of products.csv : (100, 5)
trying to save  products.csv
products.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download sales.csv
sales.csv is downloaded
the shape of sales.csv : (5000, 8)
trying to save  sales.csv
sales.csv is successfully saved

## Importing Data

In [9]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

In [3]:
df_orders = pd.read_csv('../data/raw/orders.csv')
print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [88]:
df_customers = pd.read_csv('../data/raw/customers.csv')
print(df_customers.shape)
df_customers.head()

(206209, 11)

,Unnamed: 0,user_id,First Name,Surname,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [89]:
df_states = pd.read_csv('../data/raw/states.csv')
print(df_states.shape)
df_states.head()

(51, 4)

   Unnamed: 0          state     region     division
0           0    Connecticut  Northeast  New England
1           1          Maine  Northeast  New England
2           2  Massachusetts  Northeast  New England
3           3  New Hampshire  Northeast  New England
4           4   Rhode Island  Northeast  New England

In [4]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [5]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [6]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [7]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [20]:
df_orders_train = df_orders[df_orders['eval_set'] == 'train']
print(df_orders_train.shape)
df_orders_train.head()

df_orders_train.to_csv('../data/processed/orders_train.csv',index=False)

(131209, 7)

In [40]:
df_order_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_order_products_train.shape)
df_order_products_train.head()

(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

## Explore

### Orders

In [8]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [10]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [11]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [12]:
df_orders['order_id'].nunique()

3421083

In [13]:
df_orders.shape

(3421083, 7)

In [14]:
## Consistancy Check: Order ID
if df_orders['order_id'].nunique() == df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Happy

In [15]:
## 
df_orders['order_id'].nunique() == df_orders.shape[0]

True

In [16]:
df_orders['user_id'].nunique()

206209

In [17]:
df_orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [21]:
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [22]:
df_orders_train.info()

<class 'pandas.DataFrame'>
Index: 131209 entries, 10 to 3421082
Data columns (total 7 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                131209 non-null  int64
 1   user_id                 131209 non-null  int64
 2   eval_set                131209 non-null  str
 3   order_number            131209 non-null  int64
 4   order_dow               131209 non-null  int64
 5   order_hour_of_day       131209 non-null  int64
 6   days_since_prior_order  131209 non-null  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 8.6 MB

In [23]:
columns_to_explore =['order_dow','order_hour_of_day','days_since_prior_order']

df_orders_train[columns_to_explore].describe()

       order_dow  order_hour_of_day  days_since_prior_order
count 131,209.00         131,209.00              131,209.00
mean        2.77              13.58                   17.05
std         2.12               4.22                   10.68
min         0.00               0.00                    0.00
25%         1.00              10.00                    7.00
50%         3.00              14.00                   15.00
75%         5.00              17.00                   30.00
max         6.00              23.00                   30.00

In [24]:
df_orders_train['order_id'].nunique()

131209

In [25]:
df_orders_train['user_id'].nunique()

131209

In [26]:
df_orders['order_id'].nunique()

3421083

In [27]:
df_orders['user_id'].nunique()

206209

In [28]:
df_orders['eval_set'].value_counts(normalize=True)

eval_set
prior   0.94
train   0.04
test    0.02
Name: proportion, dtype: float64

In [29]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [30]:
df_orders['order_dow'].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [31]:
df_orders['order_hour_of_day'].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [32]:
df_orders['order_hour_of_day'].between(0,23).all()

np.True_

In [36]:
df_orders['weekend'] = ['Weekend' if i in  [0,6] else 'Workday' for i in df_orders['order_dow']]
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,weekend
0,2539329,1,prior,1,2,8,NaN,Workday
1,2398795,1,prior,2,3,7,15.00,Workday
2,473747,1,prior,3,3,12,21.00,Workday
3,2254736,1,prior,4,4,7,29.00,Workday
4,431534,1,prior,5,4,15,28.00,Workday

In [37]:
df_orders['weekend'].value_counts(normalize=True)

weekend
Workday   0.69
Weekend   0.31
Name: proportion, dtype: float64

### Customers

In [90]:
df_customers.head()

,Unnamed: 0,user_id,First Name,Surname,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [91]:
df_customers['Gender'].value_counts(normalize=True)

Gender
Male     0.50
Female   0.50
Name: proportion, dtype: float64

In [92]:
df_customers[['n_dependants','fam_status']].value_counts(normalize=True)

n_dependants  fam_status
3             married                            0.23
1             married                            0.23
2             married                            0.23
0             single                             0.16
              divorced/widowed                   0.09
2             living with parents and siblings   0.02
1             living with parents and siblings   0.02
3             living with parents and siblings   0.02
Name: proportion, dtype: float64

In [93]:
df_customers[['Age','income']].describe().drop(['count'])

       Age     income
mean 49.50  94,632.85
std  18.48  42,473.79
min  18.00  25,903.00
25%  33.00  59,874.00
50%  49.00  93,547.00
75%  66.00 124,244.00
max  81.00 593,901.00

### Product_Train

In [41]:
df_order_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [42]:
df_order_products_train.shape

(1384617, 4)

In [43]:
df_products[df_products['product_id']==24852]

       product_id product_name  aisle_id  department_id  prices
24853       24852       Banana        24              4   12.30

In [44]:
df_order_products_train[['product_id','add_to_cart_order']].value_counts()

product_id  add_to_cart_order
24852       1                    4605
13176       1                    3889
24852       2                    3199
13176       2                    2867
24852       3                    2255
                                 ...
7615        28                      1
40800       1                       1
33424       3                       1
16475       4                       1
6858        5                       1
Name: count, Length: 316364, dtype: int64

In [45]:
basket_size = len(df_order_products_train)/df_order_products_train['order_id'].nunique()

print('Averager Market Basket: ', basket_size)

Averager Market Basket:  10.552759338155157

In [46]:
df_order_products_train['product_id'].nunique()

39123

In [47]:
df_order_products_train['reordered'].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

### Products

In [49]:
df_products['product_id'].nunique()

49686

In [50]:
df_products['aisle_id'].nunique()

134

In [51]:
df_products['prices'].describe()

count   49,693.00
mean         9.99
std        453.52
min          1.00
25%          4.10
50%          7.10
75%         11.20
max     99,999.00
Name: prices, dtype: float64

In [52]:
df_departments

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

### Merge
new_df = pd.merge(left_df,right_df, on = 'id', how  = 'left')

In [53]:
df_products.head()
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [54]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left",
    indicator = True
)

df_products_departments.head(20)

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,both
1,2,All-Seasons Salt,104,13,9.30,pantry,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,both
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,both
5,6,Dry Nose Oil,11,11,2.60,personal care,both
6,7,Pure Coconut Water With Orange,98,7,4.40,beverages,both
7,8,Cut Russet Potatoes Steam N' Mash,116,1,1.10,frozen,both
8,9,Light Strawberry Blueberry Yogurt,120,16,7.00,dairy eggs,both
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.40,beverages,both
10,11,Peach Mango Juice,31,7,2.80,beverages,both
11,12,Chocolate Fudge Layer Cake,119,1,9.40,frozen,both
12,13,Saline Nasal Mist,11,11,1.10,personal care,both
13,14,Fresh Scent Dishwasher Cleaner,74,17,6.50,household,both
14,15,Overnight Diapers Size 6,56,18,11.20,babies,both
15,16,Mint Chocolate Flavored Syrup,103,19,5.20,snacks,both
16,17,Rendered Duck Fat,35,12,17.10,meat seafood,both
17,18,Pizza for One Suprema Frozen Pizza,79,1,10.60,frozen,both
18,19,Gluten Free Quinoa Three Cheese & Mushroom Blend,63,9,12.00,dry goods pasta,both
19,20,Pomegranate Cranberry & Aloe Vera Enrich Drink,98,7,6.00,beverages,both

In [55]:
df_products_departments.dtypes

product_id          int64
product_name          str
aisle_id            int64
department_id       int64
prices            float64
department            str
_merge           category
dtype: object

In [56]:
df_products_departments['_merge'].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [57]:
df_train_transactions = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left"
)

df_train_transactions.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.00,196,1,1
1,1187899,1,train,11,4,8,14.00,25133,2,1
2,1187899,1,train,11,4,8,14.00,38928,3,1
3,1187899,1,train,11,4,8,14.00,26405,4,1
4,1187899,1,train,11,4,8,14.00,39657,5,1

In [58]:
df_train_transactions_check = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left",
    indicator=True
)

df_train_transactions_check.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,1187899,1,train,11,4,8,14.00,196,1,1,both
1,1187899,1,train,11,4,8,14.00,25133,2,1,both
2,1187899,1,train,11,4,8,14.00,38928,3,1,both
3,1187899,1,train,11,4,8,14.00,26405,4,1,both
4,1187899,1,train,11,4,8,14.00,39657,5,1,both

In [59]:
df_train_transactions_check["_merge"].value_counts()

_merge
both          1384617
left_only           0
right_only          0
Name: count, dtype: int64

In [60]:
df_train_transactions_check[
    df_train_transactions_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order, product_id, add_to_cart_order, reordered, _merge]
Index: []

In [61]:
print(df_orders_train.shape)
print(df_orders_products_train.shape)
print(df_train_transactions.shape)

(131209, 7)
(1384617, 4)
(1384617, 10)

In [63]:
df_train_transactions.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered'],
      dtype='str')

In [85]:
URL = 'https://raw.githubusercontent.com/hovhannisyan91/aca/main/lab/python/data/raw/'
l = ['customers','states']
for i in l:
    dfname = URL + i +'.csv'
    df = pd.read_csv(dfname)
    df.to_csv(f'../data/raw/{i}.csv')

In [87]:
df.head()

           state     region     division
0    Connecticut  Northeast  New England
1          Maine  Northeast  New England
2  Massachusetts  Northeast  New England
3  New Hampshire  Northeast  New England
4   Rhode Island  Northeast  New England