In [2]:
import pandas as pd

In [4]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 47, 63, 29],
    "income": [18000, 42000, 72000, 95000, 25000]
})

df_customers_dummy

  customer  age  income
0        A   22   18000
1        B   35   42000
2        C   47   72000
3        D   63   95000
4        E   29   25000

In [6]:
def age_group_label(age):
    if age < 30:
        return "Young"
    elif age < 63:
        return "Middle"
    else:
        return "Senior"

df_customers_dummy["age_group"] = df_customers_dummy["age"].apply(age_group_label)
df_customers_dummy

  customer  age  income age_group
0        A   22   18000     Young
1        B   35   42000    Middle
2        C   47   72000    Middle
3        D   63   95000    Senior
4        E   29   25000     Young

In [8]:
def income_band(income):
    if income < 30000:
        return "low income"
    elif income < 60000:
        return "Middle income"
    else:
        return "High income"

df_customers_dummy ["income_band"] = df_customers_dummy ["income"].apply(income_band)
df_customers_dummy

  customer  age  income age_group    income_band
0        A   22   18000     Young     low income
1        B   35   42000    Middle  Middle income
2        C   47   72000    Middle    High income
3        D   63   95000    Senior    High income
4        E   29   25000     Young     low income

In [9]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 47, 63, 29],
    "income": [18000, 42000, 72000, 95000, 25000]
})

df_customers_dummy

  customer  age  income
0        A   22   18000
1        B   35   42000
2        C   47   72000
3        D   63   95000
4        E   29   25000

In [ ]:
from utils import