In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)


months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [7]:
from utils_plotly import *

In [3]:
px.defaults.template = "plotly_white"

## Bar Plot Sales by Region

In [4]:
region_sales = df_plotly.groupby('region', as_index=False)['sales'].sum()
region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [5]:
fig = px.bar(
    data_frame  = region_sales,
    x = 'region',
    y = 'sales',
    title = "Total Sales by Region",
    text = 'sales'   
)

fig.update_traces(
    textposition = 'outside'
)

fig.update_layout(
    xaxis_title = '',
    yaxis_title = 'Sales'
)
fig.show()

### Simple Line Chart

In [9]:
monthly_sales = df_plotly.groupby("month",as_index=False)['sales'].sum()
monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [10]:
fig  = px.line(
    data_frame = monthly_sales,
    x = 'month',
    y = 'sales',
    markers = True,
    title = 'Monthly Sales' 

)

fig.update_layout(
    xaxis_title = 'Month',
    yaxis_title = 'Total Sales'
)

fig.show()

### Histogram

In [11]:
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [12]:
MY_VAR = 'units'
X_TITLE = 'Units'
# for i in list 
fig = px.histogram(
    data_frame = df_plotly,
    x = MY_VAR,
    nbins = 15,
    title = 'Sales Distribution'
)

fig.update_layout(
    xaxis_title = X_TITLE,
    yaxis_title = 'Frequency'
)
fig.show()

### Scatter Plot

In [20]:
fig  = px.scatter(
    data_frame = df_plotly,
    x = 'customers',
    y = 'sales',
    color =  'region',
    size = 'units',
    hover_data = ["product", 'units'],
    title = 'Customers vs Sales'
)
fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region"
)
fig.show()

In [ ]:
monthly_sales_region = (df_plotly
                        .groupby(['region','month'],as_index=False)['sales'].sum()


monthly_sales_region.head()

  region      month  sales
0   East 2024-01-01    217
1   East 2024-02-01    273
2   East 2024-03-01    250
3   East 2024-04-01    216
4   East 2024-05-01    350

In [28]:
fig = px.line(
    data_frame = monthly_sales_region,
    x="month",
    y="sales",
    color="region",
    markers=True,
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

In [29]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
             .sum()
)

region_product_sales

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958
5  South       B    716

In [32]:
fig = px.bar(
    data_frame = region_product_sales,
    x="region",
    y="sales",
    color="product",
    orientation = 'v',
    barmode="group",
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

In [33]:
fig = px.bar(
    data_frame = region_product_sales,
    x="region",
    y="sales",
    color="product",
    orientation = 'h',
    barmode="group",
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

### Donut Chart

In [34]:
product_sales = df_plotly.groupby('product', as_index= False)['sales'].sum()
product_sales

  product  sales
0       A   2699
1       B   2334

In [36]:
fig = px.pie(
    data_frame = product_sales,
    names = 'product',
    values = 'sales',
    hole = 0.5
)
fig.update_traces(textinfo="label+percent")
fig.show()

In [43]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    
    color_discrete_sequence=["#0be8a9"]
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Region"
)
fig.show()

In [ ]:
b

In [48]:
fig  = px.bar(
    data_frame = region_product_sales,
    y = 'sales',
    x = 'region',
    color = 'product',
    orientation = 'v',
    barmode = 'group',
    color_discrete_sequence=["#047456", "#13CBA9"]

)

fig.update_layout(
    # x
    # y
    legend_title  = 'Product'
)

## Change Line Colors

### Single Line Color

In [ ]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales",
    color_discrete_sequence=["crimson"]
)

fig.show()

### Multi-Line Colors

In [ ]:
min_sales_idx = monthly_sales['sales'].idxmin()

min_monthly_sales = monthly_sales.loc[min_sales_idx]
x_min = min_monthly_sales[['month']]
y_min = min_monthly_sales[['sales']]

In [58]:
max_sales_idx = monthly_sales['sales'].idxmax()

max_monthly_sales = monthly_sales.loc[max_sales_idx]
x_max = max_monthly_sales[['month']]
y_max = max_monthly_sales[['sales']]

In [59]:
monthly_sales_region

   region      month  sales
0    East 2024-01-01    217
1    East 2024-02-01    273
2    East 2024-03-01    250
3    East 2024-04-01    216
4    East 2024-05-01    350
5    East 2024-06-01    253
6   North 2024-01-01    276
7   North 2024-02-01    305
8   North 2024-03-01    282
9   North 2024-04-01    343
10  North 2024-05-01    322
11  North 2024-06-01    272
12  South 2024-01-01    314
13  South 2024-02-01    232
14  South 2024-03-01    299
15  South 2024-04-01    296
16  South 2024-05-01    262
17  South 2024-06-01    271

In [69]:
fig = px.line(
    data_frame = monthly_sales,
    x = 'month',
    y = 'sales'
    # color = 'region',
    # markers = True
)

fig.add_scatter(x = x_max, 
                y = y_max,
                mode = 'markers',
                name = 'Maximum',
                marker=dict(size=14, color="#ABEAA5"),
                )

fig.add_scatter(x = x_min, 
                y = y_min,
                mode = 'markers',
                name = 'Minimum',
                marker=dict(size=14, color="#B22E24"),
                )

fig.update_layout(
    # x
    # y
    # legend_title  = 'Region'
)

fig.show()

### Change Histogram Colors

In [61]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales",
    color_discrete_sequence=["purple"]
)

fig.show()

### Change Scatter Plot Colors

In [64]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    title="Customers vs Sales",
    color_discrete_sequence=["darkorange"]
)

fig.show()

In [65]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    title="Customers vs Sales by Region",
    color_discrete_sequence=["#3B6EAD", "#AFC4E8", "#B7C2D1"]
)

fig.show()

In [72]:
avg_sales = monthly_sales['sales'].mean()
avg_sales

np.float64(838.8333333333334)

In [80]:
fig = px.line(
    data_frame = monthly_sales,
    x = 'month',
    y = 'sales'
    # color = 'region',
    # markers = True
)

fig.add_scatter(x = x_max, 
                y = y_max,
                mode = 'markers',
                name = 'Maximum',
                marker=dict(size=14, color="#ABEAA5"),
                )

fig.add_scatter(x = x_min, 
                y = y_min,
                mode = 'markers',
                name = 'Minimum',
                marker=dict(size=14, color="#B22E24"),
                )

fig.add_hline(
            y = avg_sales,
            line_dash = 'dash',
            annotation_text  = 'Average Sales',
            annotation_position  = 'top left',
              )
fig.update_layout(
    # x
    # y
    # legend_title  = 'Region'
)

fig.show()

In [74]:
campaign_start = pd.Timestamp("2024-04-01")

In [77]:
fig = px.line(
    data_frame = monthly_sales,
    x = 'month',
    y = 'sales',

    # color = 'region',
    # markers = True
)

fig.update_yaxes(
    rangemode="tozero"
)

fig.add_scatter(x = x_max, 
                y = y_max,
                mode = 'markers',
                name = 'Maximum',
                marker=dict(size=14, color="#ABEAA5"),
                )

fig.add_scatter(x = x_min, 
                y = y_min,
                mode = 'markers',
                name = 'Minimum',
                marker=dict(size=14, color="#B22E24"),
                )

fig.add_hline(
            y = avg_sales,
            line_dash = 'dash',
            annotation_text  = 'Average Sales',
            annotation_position  = 'bottom left',
              )

fig.add_vline(
    x = campaign_start,
    line_dash = 'dot',
    line_color = 'red'

)


fig.add_annotation(
    x=campaign_start,
    y=monthly_sales["sales"].max(),
    text="Campaign Start",
    showarrow=True,
    arrowhead=2,
    ax=40,
    ay=-40
)
fig.update_layout(
    # x
    # y
    # legend_title  = 'Region'
)

fig.show()

### Highlighting the Largest Category in a Multi-Line Chart

In [82]:
monthly_region_sales = (
    df_plotly.groupby(["month", "region"], as_index=False)["sales"]
             .sum()
)

region_totals = (
    monthly_region_sales.groupby("region", as_index=False)["sales"]
                        .sum()
)

top_region = region_totals.loc[region_totals["sales"].idxmax(), "region"]

monthly_region_sales["highlight"] = np.where(
    monthly_region_sales["region"] == top_region,
    monthly_region_sales["region"],
    "Other Regions"
)

monthly_region_sales.head()

       month region  sales      highlight
0 2024-01-01   East    217  Other Regions
1 2024-01-01  North    276          North
2 2024-01-01  South    314  Other Regions
3 2024-02-01   East    273  Other Regions
4 2024-02-01  North    305          North

In [83]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="highlight",
    markers=True,
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        top_region: "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

### Highlighting the Largest Category in a Histogram

In [84]:
df_hist = df_plotly.copy()

df_hist["highlight"] = np.where(
    df_hist["region"] == top_region,
    "Highest Sales Region",
    "Other Regions"
)

df_hist.head()

,month,region,product,sales,customers,units,month_name,highlight
0,2024-01-01,North,A,182,71,38,Jan,Highest Sales Region
1,2024-01-01,North,B,94,80,30,Jan,Highest Sales Region
2,2024-01-01,South,A,182,43,12,Jan,Other Regions
3,2024-01-01,South,B,132,21,33,Jan,Other Regions
4,2024-01-01,East,A,117,21,69,Jan,Other Regions

In [85]:
fig = px.histogram(
    df_hist,
    x="sales",
    color="highlight",
    barmode="overlay",
    opacity=0.7,
    title="Distribution with Highlighted Largest Category",
    color_discrete_map={
        "Highest Sales Region": "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Count",
    legend_title=""
)

fig.show()

### Highlighting the Largest Category in a Grouped Bar Plot

In [86]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
             .sum()
)

product_totals = (
    region_product_sales.groupby("product", as_index=False)["sales"]
                        .sum()
)

top_product = product_totals.loc[product_totals["sales"].idxmax(), "product"]

region_product_sales["highlight"] = np.where(
    region_product_sales["product"] == top_product,
    top_product,
    "Other Products"
)

region_product_sales

  region product  sales       highlight
0   East       A    853               A
1   East       B    706  Other Products
2  North       A    888               A
3  North       B    912  Other Products
4  South       A    958               A
5  South       B    716  Other Products

In [87]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="highlight",
    barmode="group",
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        top_product: "#3B6EAD",
        "Other Products": "#D9D9D9"
    }
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()